
service: testService

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/get
          method: get

plugins:
  - serverless-offline